
÷
root"_tf_keras_model*∂
{"name": "dialo_gpt", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "must_restore_from_config": false, "class_name": "DialoGPT", "config": {"layer was saved without config": true}, "is_graph_network": false, "save_spec": {"input_ids": {"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [null, 201]}, "int32", "input_ids"]}, "attention_mask": {"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [null, 201]}, "int32", "attention_mask"]}}, "keras_version": "2.5.0", "backend": "tensorflow", "model_config": {"class_name": "DialoGPT"}, "training_config": {"loss": {"class_name": "SparseCategoricalCrossentropy", "config": {"reduction": "auto", "name": "sparse_categorical_crossentropy", "from_logits": false}, "shared_object_id": 0}, "metrics": [[{"class_name": "MeanMetricWrapper", "config": {"name": "accuracy", "dtype": "float32", "fn": "sparse_categorical_accuracy"}, "shared_object_id": 1}]], "weighted_metrics": null, "loss_weights": null, "optimizer_config": {"class_name": "Adam", "config": {"name": "Adam", "learning_rate": 4.999999873689376e-05, "decay": 0.0, "beta_1": 0.8999999761581421, "beta_2": 0.9990000128746033, "epsilon": 1e-07, "amsgrad": false}}}}2
÷root.koDialoGPT"_tf_keras_model*©{"name": "tfgp_t2lm_head_model", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "must_restore_from_config": false, "class_name": "TFGPT2LMHeadModel", "config": {"layer was saved without config": true}, "is_graph_network": false, "save_spec": {"input_ids": {"class_name": "TypeSpec", "type_spec": "tf.TensorSpec", "serialized": [{"class_name": "TensorShape", "items": [3, 5]}, "int32", "input_ids"]}}, "keras_version": "2.5.0", "backend": "tensorflow", "model_config": {"class_name": "TFGPT2LMHeadModel"}}2
åroot.koDialoGPT.transformer"_tf_keras_layer*”{"name": "transformer", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Custom>TFGPT2MainLayer", "config": {"name": "transformer", "trainable": true, "dtype": "float32", "config": {"return_dict": true, "output_hidden_states": false, "output_attentions": false, "torchscript": false, "use_bfloat16": false, "pruned_heads": {}, "tie_word_embeddings": true, "is_encoder_decoder": false, "is_decoder": false, "add_cross_attention": false, "tie_encoder_decoder": false, "max_length": 20, "min_length": 0, "do_sample": false, "early_stopping": false, "num_beams": 1, "num_beam_groups": 1, "diversity_penalty": 0.0, "temperature": 1.0, "top_k": 50, "top_p": 1.0, "repetition_penalty": 1.0, "length_penalty": 1.0, "no_repeat_ngram_size": 0, "encoder_no_repeat_ngram_size": 0, "bad_words_ids": null, "num_return_sequences": 1, "chunk_size_feed_forward": 0, "output_scores": false, "return_dict_in_generate": false, "architectures": ["GPT2LMHeadModel"], "finetuning_task": null, "id2label": {"0": "LABEL_0", "1": "LABEL_1"}, "label2id": {"LABEL_0": 0, "LABEL_1": 1}, "tokenizer_class": null, "prefix": null, "bos_token_id": 0, "pad_token_id": 3, "eos_token_id": 1, "sep_token_id": null, "decoder_start_token_id": null, "task_specific_params": {"conversational": {"max_length": 1000}}, "xla_device": null, "_name_or_path": "byeongal/Ko-DialoGPT", "author": "Heewon Jeon(madjakarta@gmail.com)", "created_date": "2021-04-28", "license": "CC-BY-NC-SA 4.0", "model_type": "gpt2", "scale_attn_weights": true, "vocab_size": 51200, "n_ctx": 1024, "n_positions": 1024, "n_embd": 768, "n_layer": 12, "n_head": 12, "n_inner": null, "activation_function": "gelu_new", "resid_pdrop": 0.1, "embd_pdrop": 0.1, "attn_pdrop": 0.1, "layer_norm_epsilon": 1e-05, "initializer_range": 0.02, "summary_type": "cls_index", "summary_use_proj": true, "summary_activation": null, "summary_first_dropout": 0.1, "summary_proj_to_labels": true, "gradient_checkpointing": false, "use_cache": true, "transformers_version": "4.3.3"}}, "shared_object_id": 2}2
Í´root.koDialoGPT.transformer.wte"_tf_keras_layer*¨{"name": "wte", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFSharedEmbeddings", "config": {"name": "wte", "trainable": true, "dtype": "float32", "vocab_size": 51200, "hidden_size": 768, "initializer_range": 0.02}, "shared_object_id": 3, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5]}}2
Ã¨root.koDialoGPT.transformer.wpe"_tf_keras_layer*é{"name": "wpe", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": {"class_name": "__tuple__", "items": [null, null]}, "stateful": false, "must_restore_from_config": false, "class_name": "Embedding", "config": {"name": "wpe", "trainable": true, "batch_input_shape": {"class_name": "__tuple__", "items": [null, null]}, "dtype": "float32", "input_dim": 1024, "output_dim": 768, "embeddings_initializer": {"class_name": "TruncatedNormal", "config": {"mean": 0.0, "stddev": 0.02, "seed": null}, "shared_object_id": 4}, "embeddings_regularizer": null, "activity_regularizer": null, "embeddings_constraint": null, "mask_zero": false, "input_length": null}, "shared_object_id": 5, "build_input_shape": {"class_name": "TensorShape", "items": [1, 5]}}2
é≠ root.koDialoGPT.transformer.drop"_tf_keras_layer*œ{"name": "dropout", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 6}2
¯Ø root.koDialoGPT.transformer.ln_f"_tf_keras_layer*π{"name": "ln_f", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "ln_f", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 1e-05, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 7}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 8}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 9, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
∫∫root.keras_api.metrics.0"_tf_keras_metric*Ç{"class_name": "Mean", "name": "loss", "dtype": "float32", "config": {"name": "loss", "dtype": "float32"}, "shared_object_id": 10}2
Ûªroot.keras_api.metrics.1"_tf_keras_metric*ª{"class_name": "MeanMetricWrapper", "name": "accuracy", "dtype": "float32", "config": {"name": "accuracy", "dtype": "float32", "fn": "sparse_categorical_accuracy"}, "shared_object_id": 1}2
≤»root.koDialoGPT.transformer.h.0"_tf_keras_layer*Ù{"name": "h_._0", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFBlock", "config": {"layer was saved without config": true}}2
≤…root.koDialoGPT.transformer.h.1"_tf_keras_layer*Ù{"name": "h_._1", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFBlock", "config": {"layer was saved without config": true}}2
≤ root.koDialoGPT.transformer.h.2"_tf_keras_layer*Ù{"name": "h_._2", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFBlock", "config": {"layer was saved without config": true}}2
≤Àroot.koDialoGPT.transformer.h.3"_tf_keras_layer*Ù{"name": "h_._3", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFBlock", "config": {"layer was saved without config": true}}2
≤Ãroot.koDialoGPT.transformer.h.4"_tf_keras_layer*Ù{"name": "h_._4", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFBlock", "config": {"layer was saved without config": true}}2
≤Õroot.koDialoGPT.transformer.h.5"_tf_keras_layer*Ù{"name": "h_._5", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFBlock", "config": {"layer was saved without config": true}}2
≤Œroot.koDialoGPT.transformer.h.6"_tf_keras_layer*Ù{"name": "h_._6", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFBlock", "config": {"layer was saved without config": true}}2
≤œroot.koDialoGPT.transformer.h.7"_tf_keras_layer*Ù{"name": "h_._7", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFBlock", "config": {"layer was saved without config": true}}2
≤–root.koDialoGPT.transformer.h.8"_tf_keras_layer*Ù{"name": "h_._8", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFBlock", "config": {"layer was saved without config": true}}2
≤—root.koDialoGPT.transformer.h.9"_tf_keras_layer*Ù{"name": "h_._9", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFBlock", "config": {"layer was saved without config": true}}2
¥“ root.koDialoGPT.transformer.h.10"_tf_keras_layer*ı{"name": "h_._10", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFBlock", "config": {"layer was saved without config": true}}2
¥” root.koDialoGPT.transformer.h.11"_tf_keras_layer*ı{"name": "h_._11", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFBlock", "config": {"layer was saved without config": true}}2
ˇˆ$root.koDialoGPT.transformer.h.0.ln_1"_tf_keras_layer*º{"name": "ln_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "ln_1", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 1e-05, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 11}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 12}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 13, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
∫˜$root.koDialoGPT.transformer.h.0.attn"_tf_keras_layer*˜{"name": "attn", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFAttention", "config": {"layer was saved without config": true}}2
ˇ¯$root.koDialoGPT.transformer.h.0.ln_2"_tf_keras_layer*º{"name": "ln_2", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "ln_2", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 1e-05, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 14}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 15}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 16, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
≤˘#root.koDialoGPT.transformer.h.0.mlp"_tf_keras_layer*{"name": "mlp", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFMLP", "config": {"layer was saved without config": true}}2
ˇ˛$root.koDialoGPT.transformer.h.1.ln_1"_tf_keras_layer*º{"name": "ln_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "ln_1", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 1e-05, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 17}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 18}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 19, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
∫ˇ$root.koDialoGPT.transformer.h.1.attn"_tf_keras_layer*˜{"name": "attn", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFAttention", "config": {"layer was saved without config": true}}2
ˇÄ$root.koDialoGPT.transformer.h.1.ln_2"_tf_keras_layer*º{"name": "ln_2", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "ln_2", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 1e-05, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 20}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 21}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 22, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
≤Å#root.koDialoGPT.transformer.h.1.mlp"_tf_keras_layer*{"name": "mlp", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFMLP", "config": {"layer was saved without config": true}}2
ˇÜ$root.koDialoGPT.transformer.h.2.ln_1"_tf_keras_layer*º{"name": "ln_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "ln_1", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 1e-05, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 23}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 24}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 25, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
∫á$root.koDialoGPT.transformer.h.2.attn"_tf_keras_layer*˜{"name": "attn", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFAttention", "config": {"layer was saved without config": true}}2
ˇà$root.koDialoGPT.transformer.h.2.ln_2"_tf_keras_layer*º{"name": "ln_2", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "ln_2", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 1e-05, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 26}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 27}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 28, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
≤â#root.koDialoGPT.transformer.h.2.mlp"_tf_keras_layer*{"name": "mlp", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFMLP", "config": {"layer was saved without config": true}}2
ˇé$root.koDialoGPT.transformer.h.3.ln_1"_tf_keras_layer*º{"name": "ln_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "ln_1", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 1e-05, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 29}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 30}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 31, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
∫è$root.koDialoGPT.transformer.h.3.attn"_tf_keras_layer*˜{"name": "attn", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFAttention", "config": {"layer was saved without config": true}}2
ˇê$root.koDialoGPT.transformer.h.3.ln_2"_tf_keras_layer*º{"name": "ln_2", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "ln_2", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 1e-05, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 32}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 33}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 34, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
≤ë#root.koDialoGPT.transformer.h.3.mlp"_tf_keras_layer*{"name": "mlp", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFMLP", "config": {"layer was saved without config": true}}2
ˇñ$root.koDialoGPT.transformer.h.4.ln_1"_tf_keras_layer*º{"name": "ln_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "ln_1", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 1e-05, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 35}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 36}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 37, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
∫ó$root.koDialoGPT.transformer.h.4.attn"_tf_keras_layer*˜{"name": "attn", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFAttention", "config": {"layer was saved without config": true}}2
ˇò$root.koDialoGPT.transformer.h.4.ln_2"_tf_keras_layer*º{"name": "ln_2", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "ln_2", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 1e-05, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 38}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 39}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 40, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
≤ô#root.koDialoGPT.transformer.h.4.mlp"_tf_keras_layer*{"name": "mlp", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFMLP", "config": {"layer was saved without config": true}}2
ˇû$root.koDialoGPT.transformer.h.5.ln_1"_tf_keras_layer*º{"name": "ln_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "ln_1", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 1e-05, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 41}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 42}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 43, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
∫ü$root.koDialoGPT.transformer.h.5.attn"_tf_keras_layer*˜{"name": "attn", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFAttention", "config": {"layer was saved without config": true}}2
ˇ†$root.koDialoGPT.transformer.h.5.ln_2"_tf_keras_layer*º{"name": "ln_2", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "ln_2", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 1e-05, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 44}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 45}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 46, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
≤°#root.koDialoGPT.transformer.h.5.mlp"_tf_keras_layer*{"name": "mlp", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFMLP", "config": {"layer was saved without config": true}}2
ˇ¶$root.koDialoGPT.transformer.h.6.ln_1"_tf_keras_layer*º{"name": "ln_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "ln_1", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 1e-05, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 47}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 48}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 49, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
∫ß$root.koDialoGPT.transformer.h.6.attn"_tf_keras_layer*˜{"name": "attn", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFAttention", "config": {"layer was saved without config": true}}2
ˇ®$root.koDialoGPT.transformer.h.6.ln_2"_tf_keras_layer*º{"name": "ln_2", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "ln_2", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 1e-05, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 50}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 51}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 52, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
≤©#root.koDialoGPT.transformer.h.6.mlp"_tf_keras_layer*{"name": "mlp", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFMLP", "config": {"layer was saved without config": true}}2
ˇÆ$root.koDialoGPT.transformer.h.7.ln_1"_tf_keras_layer*º{"name": "ln_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "ln_1", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 1e-05, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 53}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 54}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 55, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
∫Ø$root.koDialoGPT.transformer.h.7.attn"_tf_keras_layer*˜{"name": "attn", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFAttention", "config": {"layer was saved without config": true}}2
ˇ∞$root.koDialoGPT.transformer.h.7.ln_2"_tf_keras_layer*º{"name": "ln_2", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "ln_2", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 1e-05, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 56}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 57}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 58, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
≤±#root.koDialoGPT.transformer.h.7.mlp"_tf_keras_layer*{"name": "mlp", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFMLP", "config": {"layer was saved without config": true}}2
ˇ∂$root.koDialoGPT.transformer.h.8.ln_1"_tf_keras_layer*º{"name": "ln_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "ln_1", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 1e-05, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 59}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 60}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 61, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
∫∑$root.koDialoGPT.transformer.h.8.attn"_tf_keras_layer*˜{"name": "attn", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFAttention", "config": {"layer was saved without config": true}}2
ˇ∏$root.koDialoGPT.transformer.h.8.ln_2"_tf_keras_layer*º{"name": "ln_2", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "ln_2", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 1e-05, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 62}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 63}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 64, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
≤π#root.koDialoGPT.transformer.h.8.mlp"_tf_keras_layer*{"name": "mlp", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFMLP", "config": {"layer was saved without config": true}}2
ˇæ$root.koDialoGPT.transformer.h.9.ln_1"_tf_keras_layer*º{"name": "ln_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "ln_1", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 1e-05, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 65}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 66}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 67, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
∫ø$root.koDialoGPT.transformer.h.9.attn"_tf_keras_layer*˜{"name": "attn", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFAttention", "config": {"layer was saved without config": true}}2
ˇ¿$root.koDialoGPT.transformer.h.9.ln_2"_tf_keras_layer*º{"name": "ln_2", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "ln_2", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 1e-05, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 68}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 69}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 70, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
≤¡#root.koDialoGPT.transformer.h.9.mlp"_tf_keras_layer*{"name": "mlp", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFMLP", "config": {"layer was saved without config": true}}2
Ä∆%root.koDialoGPT.transformer.h.10.ln_1"_tf_keras_layer*º{"name": "ln_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "ln_1", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 1e-05, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 71}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 72}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 73, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
ª«%root.koDialoGPT.transformer.h.10.attn"_tf_keras_layer*˜{"name": "attn", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFAttention", "config": {"layer was saved without config": true}}2
Ä»%root.koDialoGPT.transformer.h.10.ln_2"_tf_keras_layer*º{"name": "ln_2", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "ln_2", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 1e-05, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 74}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 75}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 76, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
≥…$root.koDialoGPT.transformer.h.10.mlp"_tf_keras_layer*{"name": "mlp", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFMLP", "config": {"layer was saved without config": true}}2
ÄŒ%root.koDialoGPT.transformer.h.11.ln_1"_tf_keras_layer*º{"name": "ln_1", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "ln_1", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 1e-05, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 77}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 78}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 79, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
ªœ%root.koDialoGPT.transformer.h.11.attn"_tf_keras_layer*˜{"name": "attn", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFAttention", "config": {"layer was saved without config": true}}2
Ä–%root.koDialoGPT.transformer.h.11.ln_2"_tf_keras_layer*º{"name": "ln_2", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "LayerNormalization", "config": {"name": "ln_2", "trainable": true, "dtype": "float32", "axis": [2], "epsilon": 1e-05, "center": true, "scale": true, "beta_initializer": {"class_name": "Zeros", "config": {}, "shared_object_id": 80}, "gamma_initializer": {"class_name": "Ones", "config": {}, "shared_object_id": 81}, "beta_regularizer": null, "gamma_regularizer": null, "beta_constraint": null, "gamma_constraint": null}, "shared_object_id": 82, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
≥—$root.koDialoGPT.transformer.h.11.mlp"_tf_keras_layer*{"name": "mlp", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFMLP", "config": {"layer was saved without config": true}}2
ã‡+root.koDialoGPT.transformer.h.0.attn.c_attn"_tf_keras_layer*¡{"name": "c_attn", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
ã·+root.koDialoGPT.transformer.h.0.attn.c_proj"_tf_keras_layer*¡{"name": "c_proj", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
§‚1root.koDialoGPT.transformer.h.0.attn.attn_dropout"_tf_keras_layer*‘{"name": "dropout_1", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_1", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 83}2
•„2root.koDialoGPT.transformer.h.0.attn.resid_dropout"_tf_keras_layer*‘{"name": "dropout_2", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_2", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 84}2
ÜÌ(root.koDialoGPT.transformer.h.0.mlp.c_fc"_tf_keras_layer*ø{"name": "c_fc", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
ãÓ*root.koDialoGPT.transformer.h.0.mlp.c_proj"_tf_keras_layer*¬{"name": "c_proj", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 3072]}}2
ûÔ+root.koDialoGPT.transformer.h.0.mlp.dropout"_tf_keras_layer*‘{"name": "dropout_3", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_3", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 85}2
ã˛+root.koDialoGPT.transformer.h.1.attn.c_attn"_tf_keras_layer*¡{"name": "c_attn", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
ãˇ+root.koDialoGPT.transformer.h.1.attn.c_proj"_tf_keras_layer*¡{"name": "c_proj", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
§Ä1root.koDialoGPT.transformer.h.1.attn.attn_dropout"_tf_keras_layer*‘{"name": "dropout_4", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_4", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 86}2
•Å2root.koDialoGPT.transformer.h.1.attn.resid_dropout"_tf_keras_layer*‘{"name": "dropout_5", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_5", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 87}2
Üã(root.koDialoGPT.transformer.h.1.mlp.c_fc"_tf_keras_layer*ø{"name": "c_fc", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
ãå*root.koDialoGPT.transformer.h.1.mlp.c_proj"_tf_keras_layer*¬{"name": "c_proj", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 3072]}}2
ûç+root.koDialoGPT.transformer.h.1.mlp.dropout"_tf_keras_layer*‘{"name": "dropout_6", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_6", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 88}2
ãú+root.koDialoGPT.transformer.h.2.attn.c_attn"_tf_keras_layer*¡{"name": "c_attn", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
ãù+root.koDialoGPT.transformer.h.2.attn.c_proj"_tf_keras_layer*¡{"name": "c_proj", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
§û1root.koDialoGPT.transformer.h.2.attn.attn_dropout"_tf_keras_layer*‘{"name": "dropout_7", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_7", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 89}2
•ü2root.koDialoGPT.transformer.h.2.attn.resid_dropout"_tf_keras_layer*‘{"name": "dropout_8", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_8", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 90}2
Ü©(root.koDialoGPT.transformer.h.2.mlp.c_fc"_tf_keras_layer*ø{"name": "c_fc", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
ã™*root.koDialoGPT.transformer.h.2.mlp.c_proj"_tf_keras_layer*¬{"name": "c_proj", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 3072]}}2
û´+root.koDialoGPT.transformer.h.2.mlp.dropout"_tf_keras_layer*‘{"name": "dropout_9", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_9", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 91}2
ã∫+root.koDialoGPT.transformer.h.3.attn.c_attn"_tf_keras_layer*¡{"name": "c_attn", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
ãª+root.koDialoGPT.transformer.h.3.attn.c_proj"_tf_keras_layer*¡{"name": "c_proj", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
¶º1root.koDialoGPT.transformer.h.3.attn.attn_dropout"_tf_keras_layer*÷{"name": "dropout_10", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_10", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 92}2
ßΩ2root.koDialoGPT.transformer.h.3.attn.resid_dropout"_tf_keras_layer*÷{"name": "dropout_11", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_11", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 93}2
Ü«(root.koDialoGPT.transformer.h.3.mlp.c_fc"_tf_keras_layer*ø{"name": "c_fc", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
ã»*root.koDialoGPT.transformer.h.3.mlp.c_proj"_tf_keras_layer*¬{"name": "c_proj", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 3072]}}2
†…+root.koDialoGPT.transformer.h.3.mlp.dropout"_tf_keras_layer*÷{"name": "dropout_12", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_12", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 94}2
ãÿ+root.koDialoGPT.transformer.h.4.attn.c_attn"_tf_keras_layer*¡{"name": "c_attn", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
ãŸ+root.koDialoGPT.transformer.h.4.attn.c_proj"_tf_keras_layer*¡{"name": "c_proj", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
¶⁄1root.koDialoGPT.transformer.h.4.attn.attn_dropout"_tf_keras_layer*÷{"name": "dropout_13", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_13", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 95}2
ß€2root.koDialoGPT.transformer.h.4.attn.resid_dropout"_tf_keras_layer*÷{"name": "dropout_14", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_14", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 96}2
ÜÂ(root.koDialoGPT.transformer.h.4.mlp.c_fc"_tf_keras_layer*ø{"name": "c_fc", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
ãÊ*root.koDialoGPT.transformer.h.4.mlp.c_proj"_tf_keras_layer*¬{"name": "c_proj", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 3072]}}2
†Á+root.koDialoGPT.transformer.h.4.mlp.dropout"_tf_keras_layer*÷{"name": "dropout_15", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_15", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 97}2
ãˆ+root.koDialoGPT.transformer.h.5.attn.c_attn"_tf_keras_layer*¡{"name": "c_attn", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
ã˜+root.koDialoGPT.transformer.h.5.attn.c_proj"_tf_keras_layer*¡{"name": "c_proj", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
¶¯1root.koDialoGPT.transformer.h.5.attn.attn_dropout"_tf_keras_layer*÷{"name": "dropout_16", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_16", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 98}2
ß˘2root.koDialoGPT.transformer.h.5.attn.resid_dropout"_tf_keras_layer*÷{"name": "dropout_17", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_17", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 99}2
ÜÉ(root.koDialoGPT.transformer.h.5.mlp.c_fc"_tf_keras_layer*ø{"name": "c_fc", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
ãÑ*root.koDialoGPT.transformer.h.5.mlp.c_proj"_tf_keras_layer*¬{"name": "c_proj", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 3072]}}2
°Ö+root.koDialoGPT.transformer.h.5.mlp.dropout"_tf_keras_layer*◊{"name": "dropout_18", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_18", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 100}2
ãî+root.koDialoGPT.transformer.h.6.attn.c_attn"_tf_keras_layer*¡{"name": "c_attn", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
ãï+root.koDialoGPT.transformer.h.6.attn.c_proj"_tf_keras_layer*¡{"name": "c_proj", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
ßñ1root.koDialoGPT.transformer.h.6.attn.attn_dropout"_tf_keras_layer*◊{"name": "dropout_19", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_19", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 101}2
®ó2root.koDialoGPT.transformer.h.6.attn.resid_dropout"_tf_keras_layer*◊{"name": "dropout_20", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_20", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 102}2
Ü°(root.koDialoGPT.transformer.h.6.mlp.c_fc"_tf_keras_layer*ø{"name": "c_fc", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
ã¢*root.koDialoGPT.transformer.h.6.mlp.c_proj"_tf_keras_layer*¬{"name": "c_proj", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 3072]}}2
°£+root.koDialoGPT.transformer.h.6.mlp.dropout"_tf_keras_layer*◊{"name": "dropout_21", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_21", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 103}2
ã≤+root.koDialoGPT.transformer.h.7.attn.c_attn"_tf_keras_layer*¡{"name": "c_attn", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
ã≥+root.koDialoGPT.transformer.h.7.attn.c_proj"_tf_keras_layer*¡{"name": "c_proj", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
ß¥1root.koDialoGPT.transformer.h.7.attn.attn_dropout"_tf_keras_layer*◊{"name": "dropout_22", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_22", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 104}2
®µ2root.koDialoGPT.transformer.h.7.attn.resid_dropout"_tf_keras_layer*◊{"name": "dropout_23", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_23", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 105}2
Üø(root.koDialoGPT.transformer.h.7.mlp.c_fc"_tf_keras_layer*ø{"name": "c_fc", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
ã¿*root.koDialoGPT.transformer.h.7.mlp.c_proj"_tf_keras_layer*¬{"name": "c_proj", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 3072]}}2
°¡+root.koDialoGPT.transformer.h.7.mlp.dropout"_tf_keras_layer*◊{"name": "dropout_24", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_24", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 106}2
ã–+root.koDialoGPT.transformer.h.8.attn.c_attn"_tf_keras_layer*¡{"name": "c_attn", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
ã—+root.koDialoGPT.transformer.h.8.attn.c_proj"_tf_keras_layer*¡{"name": "c_proj", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
ß“1root.koDialoGPT.transformer.h.8.attn.attn_dropout"_tf_keras_layer*◊{"name": "dropout_25", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_25", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 107}2
®”2root.koDialoGPT.transformer.h.8.attn.resid_dropout"_tf_keras_layer*◊{"name": "dropout_26", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_26", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 108}2
Ü›(root.koDialoGPT.transformer.h.8.mlp.c_fc"_tf_keras_layer*ø{"name": "c_fc", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
ãﬁ*root.koDialoGPT.transformer.h.8.mlp.c_proj"_tf_keras_layer*¬{"name": "c_proj", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 3072]}}2
°ﬂ+root.koDialoGPT.transformer.h.8.mlp.dropout"_tf_keras_layer*◊{"name": "dropout_27", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_27", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 109}2
ãÓ+root.koDialoGPT.transformer.h.9.attn.c_attn"_tf_keras_layer*¡{"name": "c_attn", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
ãÔ+root.koDialoGPT.transformer.h.9.attn.c_proj"_tf_keras_layer*¡{"name": "c_proj", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
ß1root.koDialoGPT.transformer.h.9.attn.attn_dropout"_tf_keras_layer*◊{"name": "dropout_28", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_28", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 110}2
®Ò2root.koDialoGPT.transformer.h.9.attn.resid_dropout"_tf_keras_layer*◊{"name": "dropout_29", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_29", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 111}2
Ü˚(root.koDialoGPT.transformer.h.9.mlp.c_fc"_tf_keras_layer*ø{"name": "c_fc", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
ã¸*root.koDialoGPT.transformer.h.9.mlp.c_proj"_tf_keras_layer*¬{"name": "c_proj", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 3072]}}2
°˝+root.koDialoGPT.transformer.h.9.mlp.dropout"_tf_keras_layer*◊{"name": "dropout_30", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_30", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 112}2
åå,root.koDialoGPT.transformer.h.10.attn.c_attn"_tf_keras_layer*¡{"name": "c_attn", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
åç,root.koDialoGPT.transformer.h.10.attn.c_proj"_tf_keras_layer*¡{"name": "c_proj", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
®é2root.koDialoGPT.transformer.h.10.attn.attn_dropout"_tf_keras_layer*◊{"name": "dropout_31", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_31", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 113}2
©è3root.koDialoGPT.transformer.h.10.attn.resid_dropout"_tf_keras_layer*◊{"name": "dropout_32", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_32", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 114}2
áô)root.koDialoGPT.transformer.h.10.mlp.c_fc"_tf_keras_layer*ø{"name": "c_fc", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
åö+root.koDialoGPT.transformer.h.10.mlp.c_proj"_tf_keras_layer*¬{"name": "c_proj", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 3072]}}2
¢õ,root.koDialoGPT.transformer.h.10.mlp.dropout"_tf_keras_layer*◊{"name": "dropout_33", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_33", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 115}2
å™,root.koDialoGPT.transformer.h.11.attn.c_attn"_tf_keras_layer*¡{"name": "c_attn", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
å´,root.koDialoGPT.transformer.h.11.attn.c_proj"_tf_keras_layer*¡{"name": "c_proj", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
®¨2root.koDialoGPT.transformer.h.11.attn.attn_dropout"_tf_keras_layer*◊{"name": "dropout_34", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_34", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 116}2
©≠3root.koDialoGPT.transformer.h.11.attn.resid_dropout"_tf_keras_layer*◊{"name": "dropout_35", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_35", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 117}2
á∑)root.koDialoGPT.transformer.h.11.mlp.c_fc"_tf_keras_layer*ø{"name": "c_fc", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 768]}}2
å∏+root.koDialoGPT.transformer.h.11.mlp.c_proj"_tf_keras_layer*¬{"name": "c_proj", "trainable": true, "expects_training_arg": false, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "TFConv1D", "config": {"layer was saved without config": true}, "build_input_shape": {"class_name": "TensorShape", "items": [3, 5, 3072]}}2
¢π,root.koDialoGPT.transformer.h.11.mlp.dropout"_tf_keras_layer*◊{"name": "dropout_36", "trainable": true, "expects_training_arg": true, "dtype": "float32", "batch_input_shape": null, "stateful": false, "must_restore_from_config": false, "class_name": "Dropout", "config": {"name": "dropout_36", "trainable": true, "dtype": "float32", "rate": 0.1, "noise_shape": null, "seed": null}, "shared_object_id": 118}2